name: Selenium C# Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger

jobs:
  selenium-tests:
    runs-on: windows-latest  # Windows for running C# Selenium tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the code

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.0.x'  # Adjust according to your project

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Selenium Tests
        run: dotnet test --configuration Release --logger trx --results-directory TestResults
        continue-on-error: true  # Continue execution even if tests fail

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults

      - name: Convert TRX to HTML (if needed)
        run: |
          mkdir -p TestResults/HtmlReport
          dotnet tool install --global trx2html
          trx2html -i TestResults/*.trx -o TestResults/HtmlReport/TestReport.html

      - name: Send Email with Test Results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Selenium Test Report"
          body: "The latest Selenium test report is attached."
          to: "recipient@example.com"
          from: "GitHub Actions <${{ secrets.EMAIL_USERNAME }}>"
          attachments: TestResults/HtmlReport/TestReport.html
